### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by fzyzcjy** [albertqjiang/INT#4]
When I started my first open source lib, someone told me that "no license means all code are copyrighted" (see: https://github.com/fzyzcjy/flutter_rust_bridge/issues/1). Thus, I would appreciate it if this repository can have an explicit license (e.g. https://github.com/facebookresearch/miniF2F/blob/main/LICENSE), such that I can use it in my research.

**Comment by albertqjiang** [comment]
Added MIT license. Thanks!!
